services:
  - type: web
    name: bee-health-detection
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DATABASE_HOST
        value: "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
      - key: DATABASE_PORT
        value: "4000"
      - key: DATABASE_USER
        value: "AuodAvJoZCm93fv.root"
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_NAME
        value: "bee_detection"
      - key: DATABASE_SSL
        value: "true"
